"""empty message

Revision ID: 030d97860654
Revises: 4d4b38e3b04e
Create Date: 2025-08-20 11:54:01.715238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030d97860654'
down_revision = '4d4b38e3b04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('data')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
