"""add is_verified to businesses

Revision ID: 11703d5711c9
Revises: 8df1e61eec5a
Create Date: 2026-05-04 11:49:47.301493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11703d5711c9'
down_revision = '8df1e61eec5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
