"""empty message

Revision ID: 254d385beb9b
Revises: 030d97860654
Create Date: 2025-08-20 23:32:26.466582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254d385beb9b'
down_revision = '030d97860654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
