"""user data update

Revision ID: 451ebe2eb9e3
Revises: 254d385beb9b
Create Date: 2025-08-29 11:56:47.570941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451ebe2eb9e3'
down_revision = '254d385beb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
