"""add buisness id coloumn to invoices

Revision ID: 66250cd69647
Revises: a3aa4cb8b8b8
Create Date: 2025-08-20 23:47:36.638359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66250cd69647'
down_revision = 'a3aa4cb8b8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
