"""add paystack_subaccount_code to businesses

Revision ID: 8df1e61eec5a
Revises: 451ebe2eb9e3
Create Date: 2026-05-04 08:49:00.133476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df1e61eec5a'
down_revision = '451ebe2eb9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_subaccount_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('paystack_subaccount_code')

    # ### end Alembic commands ###
